eggnog:
  data_dir: '/mnt/scratch_dir/puntm/eggnog/'
  dia_db: '/mnt/scratch_dir/puntm/eggnog/euriomycetes.dmnd'
fastx-toolkit:
  blocksize: 60
fun_annotate:
  species: 'Aspergillus niger'
  database: '/mnt/scratch_dir/puntm/funannotate_db/'
interproscan:
  exec: '/mnt/scratch_dir/puntm/interproscan/interproscan-5.69-101.0/interproscan.sh'
signalp:
  models: '/mnt/scratch_dir/puntm/signalp/signalp6_fast/signalp-6-package/models/'
  directory: '/mnt/scratch_dir/puntm/signalp/signalp6_fast/pkgs/bin/signalp6'
  env: '/mnt/scratch_dir/puntm/signalp/signalp6_fast/pkgs/'