threads:
  default: 2
  helixer: 1
  fastp: 1
  fastqc: 4
  interproscan: 4
  eggnog: 32
  fun_annotate: 8
  signalp: 8
  spades: 16
mem_gb:
  default: 12
  helixer: 32
  fastp: 8
  fastqc: 8
  interproscan: 32
  eggnog: 64
  fun_annotate: 16
  signalp: 16
  spades: 16
runtime_min:
  default: 15
  spades: 180
  helixer: 15
  fastp: 60
  fastqc: 60
  interproscan: 480 #Takes about 6.5h at this stage
  eggnog: 120
  fun_annotate: 60
  signalp: 60
queue:
  default: 'bio'
  helixer: 'bio-gpu-v100'

